import type { Metadata } from "next";
import { Noto_Serif_SC, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";

const notoSerifSC = Noto_Serif_SC({
  variable: "--font-noto-serif-sc",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Nora's Blog</title>
        <script
          defer
          src="https://cloud.umami.is/script.js"
          data-website-id="b28df98a-6af9-4890-a8e7-e0fcc843804b"
        ></script>
      </head>
      <body
        className={`${notoSerifSC.variable} ${nunitoSans.variable} antialiased`}
      >
        <Nav />
        <main className="root-layout">{children}</main>
      </body>
    </html>
  );
}
